# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: 2921312
# "service" is the name of this project. This will also be added to your AWS resource names.
service: MS-CONDUCTORES
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 256 #MEMORIA ASIGNADA
  timeout: 3 #TIEMPO DE EJECUCIÓN POR FUNCIÓN
  runtimeManagement: auto #GESTIONADOR DEL RUNTIME (NODEJS20 .X) AUTO=TRUE
  versionFunctions: false #VERSIONAMIENTO DE LAS LAMBDAS - SI SE ACOPLAN MUCHAS PUEDE HABER UN COSTO ADICIONAL
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:us-east-1:975049989396:table/CONDUCTOR
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
